name: Python Backend Application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements/dev.txt

    - name: Run Autoflake
      run: |
        - autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place app --exclude=__init__.py

    - name: Run isort
      run: |
        - isort --recursive --apply app

    - name: Run Black
      run: |
        - black app

    - name: Pytest with flake8
      run: |
        pytest --flake8 --cov=app
      env:
        ALGORITHM: ${{ secrets.ALGORITHM }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
