name: Python Backend Application

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements/dev.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=88 --statistics

    - name: Pytest
      run: |
        pytest
      env:
        ALGORITHM: ${{ secrets.ALGORITHM }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
